on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - run: go version

#env GOOS=windows GOARCH=amd64 go build xxxx
# portfwd-1.0.4-linux-amd64.tar.gz

#env GOOS=linux GOARCH=amd64 go build xxx
# portfwd-v1.0.4-windows-x86_64.zip
