on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - run: |
          env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" portfwd.go
          tar zcvf portfwd-${{ github.ref }}-linux-amd64.tar.gz portfwd
          ls -la

      - run: |
          env GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w" portfwd.go
          zip portfwd-${{ github.ref }}-windows-x86_64.tar.gz portfwd.exe
          ls -la
        
